Updated

diff --git a/rarbs/src/arch b/rarbs/src/arch
--- a/rarbs/src/arch
+++ b/rarbs/src/arch
@@ -17,7 +17,7 @@ esac done
 [ -d "/sys/class/power_supply/BAT0" ] && LAPTOP=true
 [ -z "$dotfilesrepo" ] && dotfilesrepo="https://github.com/romariorobby/voidrice.git"
 if [ -z "$progsfile" ]; then
-	[ -f "$pkgdir/progs-dummy.csv" ] && progsfile="$pkgdir/progs-dummy.csv" || progsfile="https://raw.githubusercontent.com/romariorobby/RARBS/master/src/pkg/progs-arch.csv"
+	[ -f "$pkgdir/progs-arch.csv" ] && progsfile="$pkgdir/progs-arch.csv" || progsfile="https://raw.githubusercontent.com/romariorobby/RARBS/master/src/pkg/progs-arch.csv"
 fi
 if [ -z "$progsallfile" ]; then
 	[ -f "src/pkg/progs-all.csv" ] && progsallfile="src/pkg/progs-all.csv" || progsallfile="https://raw.githubusercontent.com/romariorobby/RARBS/master/src/pkg/progs-all.csv"
@@ -36,7 +36,7 @@ error() { printf "%s\n" "$1" >&2; exit 1;}
 
 finalize(){ \
 	dialog --infobox "Preparing welcome message..." 4 50
-	dialog --title "All done!" --msgbox "Congrats! Provided there were no hidden errors, the script completed successfully and all the programs and configuration files should be in place.\\n\\nTo run the new graphical environment, log out and log back in as your new user, then run the command \"startx\" to start the graphical environment (it will start automatically in tty1).\\n\\n.t Luke" 12 80
+	dialog --title "All done!" --msgbox "Congrats! Provided there were no hidden errors, the script completed successfully and all the programs and configuration files should be in place.\\n\\nTo run the new graphical environment, log out and log back in as your new user, then run the command \"startx\" to start the graphical environment (it will start automatically in tty1).\\n\\n.t Romario" 12 80
 	}
 
 load() {
@@ -108,21 +108,24 @@ maininstall() { # Installs all needed programs from main repo.
 	) & pid=$! pri=0.2 title="Main Installation" msg="[$n/$total] Installing $1 (${status})\n\n $2\n\Z1> \Z2\`pacman -S $1\`\Zn" load
 }
 
-# TODO: Seems have problem 
+# TODO: Seems have problem wtih `cd` need to go back to this file. or create temporary file for this
 aurmanualinstall() { # Installs $1 manually. Used only for AUR helper here.
 	# Should be run after repodir is created and var is set.
-#	dialog --infobox "Installing \"$1\", an AUR helper..." 4 50
+	dialog --infobox "Preparing for installing \"$1\", an AUR helper..." 4 50
+	_dir="$PWD"
+
 	(
 		sudo -u "$name" mkdir -p "$repodir/$1"
 	) & pid=$! pri=0.2 title="RARBS Installation" msg="Creating Directory\n\n blablaalb\n\Z1> \Z2\`mkdir -p $repodir/$1 \`\Zn" load
 	(
 		sudo -u "$name" git -C "$repodir/$1" clone --depth 1 "https://aur.archlinux.org/$1.git" "$repodir/$1" >/dev/null 2>&1 || \
 			{ cd "$repodir/$1" || return 1 ; sudo -u "$name" git pull --force origin master >/dev/null 2>&1;}
-	) & pid=$! pri=0.2 title="RARBS Installation" msg="Cloning $aurhelper.git\n\n blablaalb\n\Z1> \Z2\`git clone https://aur.archlinux.org/$1.git\`\Zn" load
+	) & pid=$! pri=0.2 title="RARBS Installation" msg="Cloning $aurhelper.git\n\n \n\Z1> \Z2\`git clone https://aur.archlinux.org/$1.git\`\Zn" load
 		cd "$repodir/$1"
 	(
 		sudo -u "$name" -D "$repodir/$1" makepkg --noconfirm -si >/dev/null 2>&1 || return 1
-	) & pid=$! pri=0.2 title="RARBS Installation" msg="Installing $aurhelper\n\n blablaalb\n\Z1> \Z2\`makepkg -si\`\Zn" load
+	) & pid=$! pri=0.2 title="RARBS Installation" msg="Installing $aurhelper\n\n \n\Z1> \Z2\`makepkg -si\`\Zn" load
+	cd $_dir
 }
 
 aurinstall() { \
@@ -228,13 +231,11 @@ cp -f dialogrc /root/.dialogrc
 welcomemsg || error "User exited."
 
 # Get and verify username and password.
-#getuserandpass || error "User exited."
+getuserandpass || error "User exited."
 
-name="mario"
-pass1="mario"
-# usercheck || error "User Exited"
+usercheck || error "User Exited"
 
-#refreshkeys || error "Error automatically refreshing Arch keyring. Consider doing so manually."
+refreshkeys || error "Error automatically refreshing Arch keyring. Consider doing so manually."
 
 for x in curl ca-certificates base-devel git ntp zsh; do
 	dialog --title "RARBS Installation" --infobox "Installing \`$x\` which is required to install and configure other programs." 5 70
@@ -242,15 +243,15 @@ for x in curl ca-certificates base-devel git ntp zsh; do
 done
 
 dialog --title "RARBS Installation" --infobox "Synchronizing system time to ensure successful and secure installation of software..." 4 70
-#ntpdate 0.id.pool.ntp.org >/dev/null 2>&1
+ntpdate 0.id.pool.ntp.org >/dev/null 2>&1
 
-# [ -f /etc/sudoers.pacnew ] && cp /etc/sudoers.pacnew /etc/sudoers # Just in case
+[ -f /etc/sudoers.pacnew ] && cp /etc/sudoers.pacnew /etc/sudoers # Just in case
 
 adduserandpass || error "Error adding username and/or password."
 
 # Allow user to run sudo without password. Since AUR programs must be installed
 # in a fakeroot environment, this is required for all builds with AUR.
-# newperms "%wheel ALL=(ALL) NOPASSWD: ALL"
+newperms "%wheel ALL=(ALL) NOPASSWD: ALL"
 
 # Make pacman colorful, concurrent downloads and Pacman eye-candy.
 grep -q "ILoveCandy" /etc/pacman.conf || sed -i "/#VerbosePkgLists/a ILoveCandy" /etc/pacman.conf
@@ -269,17 +270,17 @@ installationloop 2>>${ERR_FILE}
 
 
 # Make zsh the default shell for the user.
-# chsh -s /bin/zsh "$name" >/dev/null 2>&1
-# sudo -u "$name" mkdir -p "/home/$name/.cache/zsh/"
-# sudo -u "$name" mkdir -p "/home/$name/.config/abook/"
-# sudo -u "$name" mkdir -p "/home/$name/.config/mpd/playlists/"
+chsh -s /bin/zsh "$name" >/dev/null 2>&1
+sudo -u "$name" mkdir -p "/home/$name/.cache/zsh/"
+sudo -u "$name" mkdir -p "/home/$name/.config/abook/"
+sudo -u "$name" mkdir -p "/home/$name/.config/mpd/playlists/"
 
 # Artix Only
 # dbus UUID must be generated for Artix runit.
-# dbus-uuidgen > /var/lib/dbus/machine-id
+dbus-uuidgen > /var/lib/dbus/machine-id
 
 # Use system notifications for Brave on Artix
-# echo "export \$(dbus-launch)" > /etc/profile.d/dbus.sh
+echo "export \$(dbus-launch)" > /etc/profile.d/dbus.sh
 
 # Tap to click
 [ ! -f /etc/X11/xorg.conf.d/40-libinput.conf ] && printf 'Section "InputClass"
@@ -293,11 +294,11 @@ EndSection' > /etc/X11/xorg.conf.d/40-libinput.conf
 
 # This line, overwriting the `newperms` command above will allow the user to run
 # serveral important commands, `shutdown`, `reboot`, updating, etc. without a password.
-# newperms "%wheel ALL=(ALL) ALL #LARBS
-# %wheel ALL=(ALL) NOPASSWD: /usr/bin/shutdown,/usr/bin/reboot,/usr/bin/systemctl suspend,/usr/bin/wifi-menu,/usr/bin/mount,/usr/bin/umount,/usr/bin/pacman -Syu,/usr/bin/pacman -Syyu,/usr/bin/packer -Syu,/usr/bin/packer -Syyu,/usr/bin/systemctl restart NetworkManager,/usr/bin/rc-service NetworkManager restart,/usr/bin/pacman -Syyu --noconfirm,/usr/bin/loadkeys,/usr/bin/paru,/usr/bin/pacman -Syyuw --noconfirm"
+newperms "%wheel ALL=(ALL) ALL #RARBS
+%wheel ALL=(ALL) NOPASSWD: /usr/bin/shutdown,/usr/bin/reboot,/usr/bin/systemctl suspend,/usr/bin/wifi-menu,/usr/bin/mount,/usr/bin/umount,/usr/bin/pacman -Syu,/usr/bin/pacman -Syyu,/usr/bin/packer -Syu,/usr/bin/packer -Syyu,/usr/bin/systemctl restart NetworkManager,/usr/bin/rc-service NetworkManager restart,/usr/bin/pacman -Syyu --noconfirm,/usr/bin/loadkeys,/usr/bin/paru,/usr/bin/pacman -Syyuw --noconfirm"
 
 log "*** End Script ***"
 log "******************"
 
 finalize
-# clear
+clear
